// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetAccountByIdParams is parameters of getAccountById operation.
type GetAccountByIdParams struct {
	// ID of account to return.
	AccountId int64
}

func unpackGetAccountByIdParams(packed middleware.Parameters) (params GetAccountByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(int64)
	}
	return params
}

func decodeGetAccountByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAccountByIdParams, _ error) {
	// Decode path: accountId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPetByIdParams is parameters of getPetById operation.
type GetPetByIdParams struct {
	// ID of pet to return.
	PetId int64
}

func unpackGetPetByIdParams(packed middleware.Parameters) (params GetPetByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "petId",
			In:   "path",
		}
		params.PetId = packed[key].(int64)
	}
	return params
}

func decodeGetPetByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPetByIdParams, _ error) {
	// Decode path: petId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "petId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "petId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
