// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	AccountHandler
	PetHandler
}

// AccountHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Account
type AccountHandler interface {
	// GetAccountById implements getAccountById operation.
	//
	// Returns a single account.
	//
	// GET /account/{accountId}
	GetAccountById(ctx context.Context, params GetAccountByIdParams) (GetAccountByIdRes, error)
}

// PetHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Pet
type PetHandler interface {
	// AddPet implements addPet operation.
	//
	// Add a new pet to the store.
	//
	// POST /pet
	AddPet(ctx context.Context, req *Pet) (*Pet, error)
	// GetPetById implements getPetById operation.
	//
	// Returns a single pet.
	//
	// GET /pet/{petId}
	GetPetById(ctx context.Context, params GetPetByIdParams) (GetPetByIdRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
