// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddPet implements addPet operation.
//
// Add a new pet to the store.
//
// POST /pet
func (UnimplementedHandler) AddPet(ctx context.Context, req *Pet) (r *Pet, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountById implements getAccountById operation.
//
// Returns a single account.
//
// GET /account/{accountId}
func (UnimplementedHandler) GetAccountById(ctx context.Context, params GetAccountByIdParams) (r GetAccountByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPetById implements getPetById operation.
//
// Returns a single pet.
//
// GET /pet/{petId}
func (UnimplementedHandler) GetPetById(ctx context.Context, params GetPetByIdParams) (r GetPetByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}
